export const env = {
  PUBLIC_URL_ENDPOINT: import.meta.env.PUBLIC_URL_ENDPOINT,
  PUBLIC_GITHUB_SECRET: import.meta.env.PUBLIC_GITHUB_SECRET,
  PUBLIC_GITHUB_ID: import.meta.env.PUBLIC_GITHUB_ID,
  NEXTAUTH_SECRET: import.meta.env.NEXTAUTH_SECRET,
  PUBLIC_SECRET_TOKEN: import.meta.env.PUBLIC_SECRET_TOKEN,
  NEXTAUTH_URL: import.meta.env.NEXTAUTH_URL,
  PUBLIC_VERCEL_URL: import.meta.env.PUBLIC_VERCEL_URL,
  PUBLIC_PRODUCTION_URL: import.meta.env.PUBLIC_PRODUCTION_URL,
  PUBLIC_GITHUB_USERNAME: import.meta.env.PUBLIC_GITHUB_USERNAME,
  TURSO_DATABASE_URL: import.meta.env.TURSO_DATABASE_URL,
  TURSO_AUTH_TOKEN: import.meta.env.TURSO_AUTH_TOKEN,
  PUBLIC_CLOUDFLARE_TURNSTILE_SECRET_KEY: import.meta.env
    .PUBLIC_CLOUDFLARE_TURNSTILE_SECRET_KEY,
  PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: import.meta.env
    .PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY,
  EMAIL_NAME: import.meta.env.EMAIL_NAME,
  PUBLIC_DEVELOPMENT_URL: import.meta.env.PUBLIC_DEVELOPMENT_URL,
  PUBLIC_GOOGLE_SECRET: import.meta.env.PUBLIC_GOOGLE_SECRET,
  PUBLIC_GOOGLE_ID: import.meta.env.PUBLIC_GOOGLE_ID,
};
